---
- name: Provision K3s cluster
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Include repository secrets
      ansible.builtin.include_vars:
        file: ../../ansible_secrets.yaml
        name: secrets
  roles:
    - role: nfs_storage_class
      nfs_server: 192.168.101.1
      nfs_path: /backplane/applications
    - role: k8s_dashboard
    - role: cloudflare_ddns
      zone_id: "{{ secrets.cloudflare_ddns.zone_id }}"
      record_id: "{{ secrets.cloudflare_ddns.record_id }}"
      record_name: "{{ secrets.cloudflare_ddns.record_name }}"
      api_key: "{{ secrets.cloudflare_ddns.api_key }}"
      refresh_minutes: 5
      proxied: true
    - role: homer
