apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homer-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`danzek.zebra-nominal.ts.net`)
      kind: Rule
      services:
        - name: homer
          port: 8080
  tls:
    certResolver: tailscale
---
# TODO can a global redirect for the domain be created?
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homer
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`danzek.zebra-nominal.ts.net`)
      kind: Rule
      services:
        - name: homer
          port: 8080
      middlewares:
        - name: redirect-https
