---
- name: Provision K3s cluster
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Include repository secrets
      ansible.builtin.include_vars:
        file: ../../ansible_secrets.yaml
        name: secrets
  roles:
    - k8s-dashboard
    - cloudflare-ddns
    - nfs-storage-class
