# - name: Ensure required local packages are installed
#   ansible.builtin.package:
#     name: "{{ required_packages }}"
#     state: present
#     update_cache: yes
#   become: yes
- name: Ensure required python modules are installed
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    extra_args: --user
  with_items: "{{ required_pip_packages }}"
- name: Install helm diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
- name: Add Helm repositories
  kubernetes.core.helm_repository:
    repo_name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  with_items: "{{ helm_repositories }}"
