- name: Ensure djjudas21 Helm repo has been added
  kubernetes.core.helm_repository:
    name: djjudas21
    repo_url: https://djjudas21.github.io/charts/
- name: Provision Homer
  kubernetes.core.helm:
    name: homer
    chart_ref: djjudas21/homer
    release_namespace: homer
    create_namespace: true
    values:
      ingress:
        main:
          enabled: true
          hosts:
            - host: homer.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
