- name: Ensure traefik Helm repo has been added
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts
- name: Provision Traefik
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    create_namespace: true
    values: {}
