- name: Ensure traefik Helm repo has been added
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts
- name: Provision Traefik
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    create_namespace: true
    force: true
    values:
      certificatesResolvers:
        tailscale:
          tailscale: {}
      certResolvers:
        tailscale:
          tailscale: {}
- name: Install Traefik CRDs
  kubernetes.core.k8s:
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/traefik/traefik/v2.9/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml', split_lines=False) }}"
    state: present
    apply: true
- name: Create HTTPS redirect middleware
  kubernetes.core.k8s:
    src: redirect-https-middleware.yaml
    namespace: homer
    state: present
    apply: true
